version: '3.1'


services:
  spring:
    image: piglin850/swapswap:latest
    container_name: swapswap
    ports:
      - 80:8080

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379