name: Swapswap Deploy

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  continuous-delivery:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:
      - name: Docker-compose run
        run: |
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
