package piglin.swapswap.domain.post.constant;

public enum City {
    ANDONG("안동시", Province.NORTH_GYEONGSANG),
    ANSAN("안산시", Province.GYEONGGI),
    ANSEONG("안성시", Province.GYEONGGI),
    ANYANG("안양시", Province.GYEONGGI),
    ASAN("아산시", Province.SOUTH_CHUNGCHEONG),
    BORYEONG("보령시", Province.SOUTH_CHUNGCHEONG),
    BUCHEON("부천시", Province.GYEONGGI),
    BUSAN("부산광역시", Province.NONE),
    CHANGWON("창원시", Province.SOUTH_GYEONGSANG),
    CHEONAN("천안시", Province.SOUTH_CHUNGCHEONG),
    CHEONGJU("청주시", Province.NORTH_CHUNGCHEONG),
    CHUNCHEON("춘천시", Province.GANGWON),
    CHUNGJU("충주시", Province.NORTH_CHUNGCHEONG),
    DAEGU("대구광역시", Province.NONE),
    DAEJEON("대전광역시", Province.NONE),
    DANGJIN("당진시", Province.SOUTH_CHUNGCHEONG),
    DONGDUCHEON("동두천시", Province.GYEONGGI),
    DONGHAE("동해시", Province.GANGWON),
    GANGNEUNG("강릉시", Province.GANGWON),
    GEOJE("거제시", Province.SOUTH_GYEONGSANG),
    GIMCHEON("김천시", Province.NORTH_GYEONGSANG),
    GIMHAE("김해시", Province.SOUTH_GYEONGSANG),
    GIMJE("김제시", Province.NORTH_JEOLLA),
    GIMPO("김포시", Province.GYEONGGI),
    GONGJU("공주시", Province.SOUTH_CHUNGCHEONG),
    GOYANG("고양시", Province.GYEONGGI),
    GUMI("구미시", Province.NORTH_GYEONGSANG),
    GUNPO("군포시", Province.GYEONGGI),
    GUNSAN("군산시", Province.NORTH_JEOLLA),
    GURI("구리시", Province.GYEONGGI),
    GWACHEON("과천시", Province.GYEONGGI),
    GWANGJU("광주광역시", Province.NONE),
    GWANGJU_GYEONGGI("광주시", Province.GYEONGGI),
    GWANGMYEONG("광명시", Province.GYEONGGI),
    GWANGYANG("광양시", Province.SOUTH_JEOLLA),
    GYEONGJU("경주시", Province.NORTH_GYEONGSANG),
    GYEONGSAN("경산시", Province.NORTH_GYEONGSANG),
    GYERYONG("계룡시", Province.SOUTH_CHUNGCHEONG),
    HANAM("하남시", Province.GYEONGGI),
    HWASEONG("화성시", Province.GYEONGGI),
    ICHEON("이천시", Province.GYEONGGI),
    IKSAN("익산시", Province.NORTH_JEOLLA),
    INCHEON("인천광역시", Province.NONE),
    JECHEON("제천시", Province.NORTH_CHUNGCHEONG),
    JEONGEUP("정읍시", Province.NORTH_JEOLLA),
    JEONJU("전주시", Province.NORTH_JEOLLA),
    JEJU("제주시", Province.JEJU),
    JINJU("진주시", Province.SOUTH_GYEONGSANG),
    NAJU("나주시", Province.SOUTH_JEOLLA),
    NAMYANGJU("남양주시", Province.GYEONGGI),
    NAMWON("남원시", Province.NORTH_JEOLLA),
    NONSAN("논산시", Province.SOUTH_CHUNGCHEONG),
    MIRYANG("밀양시", Province.SOUTH_GYEONGSANG),
    MOKPO("목포시", Province.SOUTH_JEOLLA),
    MUNGYEONG("문경시", Province.NORTH_GYEONGSANG),
    OSAN("오산시", Province.GYEONGGI),
    PAJU("파주시", Province.GYEONGGI),
    POCHEON("포천시", Province.GYEONGGI),
    POHANG("포항시", Province.NORTH_GYEONGSANG),
    PYEONGTAEK("평택시", Province.GYEONGGI),
    SACHEON("사천시", Province.SOUTH_GYEONGSANG),
    SANGJU("상주시", Province.NORTH_GYEONGSANG),
    SAMCHEOK("삼척시", Province.GANGWON),
    SEJONG("세종특별자치시", Province.NONE),
    SEOGWIPO("서귀포시", Province.JEJU),
    SEONGNAM("성남시", Province.GYEONGGI),
    SEOSAN("서산시", Province.SOUTH_CHUNGCHEONG),
    SEOUL("서울특별시", Province.NONE),
    SIHEUNG("시흥시", Province.GYEONGGI),
    SOKCHO("속초시", Province.GANGWON),
    SUNCHEON("순천시", Province.SOUTH_JEOLLA),
    SUWON("수원시", Province.GYEONGGI),
    TAEBACK("태백시", Province.GANGWON),
    TONGYEONG("통영시", Province.SOUTH_GYEONGSANG),
    UIJEONGBU("의정부시", Province.GYEONGGI),
    UIWANG("의왕시", Province.GYEONGGI),
    ULSAN("울산광역시", Province.NONE),
    WONJU("원주시", Province.GANGWON),
    YANGJU("양주시", Province.GYEONGGI),
    YANGSAN("양산시", Province.SOUTH_GYEONGSANG),
    YEOJU("여주시", Province.GYEONGGI),
    YEONGCHEON("영천시", Province.NORTH_GYEONGSANG),
    YEONGJU("영주시", Province.NORTH_GYEONGSANG),
    YEOSU("여수시", Province.SOUTH_JEOLLA),
    YONGIN("용인시", Province.GYEONGGI);

    private final String name;
    private final Province province;

    City(String name, Province province) {
        this.name = name;
        this.province = province;
    }
}
